name = "GamersAeronauted"
author = "Gamers"
version = "4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a869c4ba310c8bb6d282a975d175c88e5b3db88725a511268e1ea57eceebdf5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
