name = "GamersAeronauted"
author = "Gamers"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8945bcff97aa328a176f200611f0daa3c04c29d90049b9951567972452f3684"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
