name = "GamersAeronauted"
author = "Gamers"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fbabda9b96dfcf366f3ac63776c6fc89263719579c38b6e327425f3a1ee1c7d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
