name = "GamersAeronauted"
author = "Gamers"
version = "4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84852c28bb51ae94f18f6f3be8932fca207d495333cb5af944ae510bb8f6f1c9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
