name = "GamersAeronauted"
author = "Gamers"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c3c2e2959f72788aa05385b5c6099a551957ce94bd192f4ec833f25114f75ff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
