name = "GamersAeronauted"
author = "Gamers"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fc3ccb11de99f41a9eaa9fdbef781197fd9c14b8a1241368fb1640b57a0cbdc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
