name = "GamersAeronauted"
author = "Gamers"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b23f3fc3be7b7fbf42cf570b26234480278257f64bf153bdd55468f819296933"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
