name = "GamersAeronauted"
author = "Gamers"
version = "dev-22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e289969ef563282aaf237d37005a8b13e713e8ffc94b002e3163ca7ccb5624b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
