name = "GamersAeronauted"
author = "Gamers"
version = "dev-36"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab07bb7080e36be5098e3f87e1f30374eb878a0a47a2a3ffc81c38ddd7d46aad"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
