name = "GamersAeronauted"
author = "Gamers"
version = "dev-69"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2234d1ddecd9ab4e6d90cc985c101923cd68e35ec70788d0e889e32974525ce6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
