name = "GamersAeronauted"
author = "Gamers"
version = "dev-20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6861d454a5f42cb1abc30c6edcc07edefe02f860f3db5ec758252459c734b811"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
