name = "GamersAeronauted"
author = "Gamers"
version = "dev-69"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8bb3e201e63e5396643cd829c2a5a0c4101f31e17a2ca13212e4c34fa8a23dc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
