name = "GamersAeronauted"
author = "Gamers"
version = "dev-59"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf867f5a4bb9806176820201fbc0b9941d94d980ca9480c5dcf7c85d12b1701f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"

[options]
no-internal-hashes = true
