hash-format = "sha256"

[[files]]
file = "config/bcc-common.toml"

[[files]]
file = "config/spore-startup.toml"

[[files]]
file = "filesToRemove.txt"

[[files]]
file = "mods/aeronautics-winds-and-weather.pw.toml"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
metafile = true

[[files]]
file = "mods/antique-atlas.pw.toml"
metafile = true

[[files]]
file = "mods/antiqueatlas.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/azimuth-api.pw.toml"
metafile = true

[[files]]
file = "mods/big-lost-city.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/cbc-compact-mount.pw.toml"
metafile = true

[[files]]
file = "mods/cc-cbc-compact-mount.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cgs.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/corail-tombstone.pw.toml"
metafile = true

[[files]]
file = "mods/corail-tompstone.pw.toml"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
metafile = true

[[files]]
file = "mods/create-aero-radars.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-transmission-linkage.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeroworks.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons-advanced-technologies.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
metafile = true

[[files]]
file = "mods/create-design-n-decor.pw.toml"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
metafile = true

[[files]]
file = "mods/create-ender-transmission.pw.toml"
metafile = true

[[files]]
file = "mods/create-prismatic-shine.pw.toml"
metafile = true

[[files]]
file = "mods/create-propulsion-simulated.pw.toml"
metafile = true

[[files]]
file = "mods/create-radars.pw.toml"
metafile = true

[[files]]
file = "mods/create-structures-arise.pw.toml"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
metafile = true

[[files]]
file = "mods/create-tfmg.pw.toml"
metafile = true

[[files]]
file = "mods/create-wrapped.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/createcybernetics.pw.toml"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/epic-fight.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
metafile = true

[[files]]
file = "mods/fungal-infectionspore.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/hypertube.pw.toml"
metafile = true

[[files]]
file = "mods/iam-music-player-renewed.pw.toml"
metafile = true

[[files]]
file = "mods/idas.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
metafile = true

[[files]]
file = "mods/integrated-api.pw.toml"
metafile = true

[[files]]
file = "mods/irons-lib.pw.toml"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-beachparty.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-farm-charm.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-vinery.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/millenaire.pw.toml"
metafile = true

[[files]]
file = "mods/modpack-helper.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/mythic-upgrades.pw.toml"
metafile = true

[[files]]
file = "mods/ntgl.pw.toml"
metafile = true

[[files]]
file = "mods/otyacraft-engine-renewed.pw.toml"
metafile = true

[[files]]
file = "mods/pb-jelly.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/power-grid.pw.toml"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
metafile = true

[[files]]
file = "mods/realm-rpg-fallen-adventurers.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rpl.pw.toml"
metafile = true

[[files]]
file = "mods/sable.pw.toml"
metafile = true

[[files]]
file = "mods/simulated-addition.pw.toml"
metafile = true

[[files]]
file = "mods/strut-your-stuff.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tacz-1.21.1.pw.toml"
metafile = true

[[files]]
file = "mods/tacz-npcs.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/unionlib.pw.toml"
metafile = true

[[files]]
file = "mods/waifucraft.pw.toml"
metafile = true

[[files]]
file = "mods/weeping-angels.pw.toml"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
metafile = true
