name = "GamersAeronauted"
author = "Gamers"
version = "dev-24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad3baa70c4451133874556b8210da601f574bc156acd50a74048bd973554f676"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
