name = "PackFramework"
author = "Den4enko"
version = "dev-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39d1d2f95f245999fa65cd4b631a23a3e615bd432138c1248fc49fc8e47943b2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
